apiVersion: v1
kind: Service
metadata:
  labels:
    app: htpc
  name: prowlarr
  namespace: media
spec:
  ports:
  - name: webui
    port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    app: htpc
    run: prowlarr