apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.107
    path: "/nfsshare"
