apiVersion: v1
data:
    TOKEN: ENC[AES256_GCM,data:eElfpng+1sj6dpoxrHT9pxO+69AN1JDvM3/z5TEARwa7dPwyAm3AkpnyTjZ4/Po9dNs+Nleb3uvqVIT9YNemO0CZvPF8tvEwbUKGgJ2afNQ=,iv:uffBatLv0CvsQRITCkjPh62L8nvncV6HJShy1YcjJBs=,tag:VKur5pnqUlU385K4y/mJHg==,type:str]
kind: Secret
metadata:
    name: discord-music-bot-secret
    namespace: media
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9wdnp870t9yy7ermhy0gq860mq2urq3fqrefut55v4tzwp3nurs43fg0s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWtITTIrV3FaYzAyNzFy
            bjNsMEkxNFk3L0pNcmdGNFRCRWVteTZoVFVBClZERnRIVlpmSUMzbncxTDVpbHZB
            MngvekZUempSUU1udnE3d3pBVjBDTVUKLS0tIE9GeEU4WjlCQUpOSi83aEVrSFZO
            cnUxKzBwZFl2N3ZuRWxTK0tia1VTdjQKBR97tOGqH+/Dxdr+R3aPtPfAij/+hwZr
            A9zrzyptEsi0CecMLPUZ07OtNUupg3sgW8YUiKj/43bH7+T8J3OopQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-01T10:19:59Z"
    mac: ENC[AES256_GCM,data:CQ7hBQkOe7NsnjHezF82tDWd61zxWpv3I3qihTw7sT7s6ENcj53aTOYO2A8QLRFz67egiVpNBk0D6X50vcafPd4qmWkacMsaw3qhh/Hq+1206uO/NUAla6yY4a5m7zBA3GXbDZ3qvvB07+FKCFkjl9soUhx8/q63s6a0M+FcrH0=,iv:e2hGBPSp0KtrgBirWwjXHqbTG1sbiu4E9+qt+NuBDbw=,tag:hzbefScwU8YVrdboo8/3dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
