---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Africa/Johannesburg"
    service:
      dns-tcp:
        enabled: false
      dns-udp:
        enabled: false
