apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: adguard-home
    meta.helm.sh/release-namespace: networking
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
    metallb.universe.tf/allow-shared-ip: "adguard-192.168.0.11"
  labels:
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
  name: adguard-tcp
  namespace: networking
spec:
  loadBalancerIP: 192.168.0.11
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
  type: LoadBalancer
