---
kubernetes:
  children:
    master:
      hosts:
        k8s-odroid-0:
          ansible_host: 192.168.0.112
          ansible_python_interpreter: /usr/bin/python3
    worker:
      hosts:
        k8s-odroid-1:
          ansible_host: 192.168.0.113
          ansible_python_interpreter: /usr/bin/python3
        k8s-odroid-2:
          ansible_host: 192.168.0.114
          ansible_python_interpreter: /usr/bin/python3
        k8s-odroid-3:
          ansible_host: 192.168.0.115
          ansible_python_interpreter: /usr/bin/python3
        k8s-odroid-4:
          ansible_host: 192.168.0.116
          ansible_python_interpreter: /usr/bin/python3
