---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: chartmuseum
      version: 3.6.2
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        kubernetes.io/ingress.class: traefik
      hosts:
        - name: "charts.${SECRET_DOMAIN}"
          path: /
          tls: true
          tlsSecret: chartmuseum-tls
    env:
      open:
        CHART_URL: "charts.${SECRET_DOMAIN}"
        DISABLE_API: "false"
        DEBUG: "true"
    persistence:
      enabled: true
      existingClaim: chartmuseum-pvc
      pv:
        nfs:
          server: ""
          path: ""
