kind: Secret
ansible_user: ENC[AES256_GCM,data:QdovRw==,iv:ZCMJI4UjondUm0jC7mqQT6Fjx/6a1/wEW7DylrqbByM=,tag:Bjxuvd4cxRXBjRw9zK6Zzw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QRWxC7DGO38=,iv:ZW5mn2GrPKDriDw5BvuDvAwM8raYDsqew3fFeKtk3II=,tag:TIui5uVvV+xxNkp7VBlSJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9wdnp870t9yy7ermhy0gq860mq2urq3fqrefut55v4tzwp3nurs43fg0s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY2h6VjJlZEwvWnhSZ01z
            QU1uUlhBQUpxUVo4RjJ5VVRsaW5XMkh3T1VRClFrR0luL29DV2ZBb0dtZ3ExQWNX
            RHFyeHhzcVNNNjhJbEpSc1ZHMW0rczQKLS0tIGNKZjVYVjNGVWVTUUZIaVkwL0o1
            VU9MbCtvT05TY3ZhNlVkbTJiQWtQQ0EK3/BN6jI92NBSRWvD8/z9+6pDYGFwDC/j
            3cPqCZad5OuhDu7zEREO46Iyo8w753BbSclsSvukpHJfsNk3vRBEsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T14:29:39Z"
    mac: ENC[AES256_GCM,data:bJyjfMbJ6qPNrVmWGfUA0zAvsal76JQHrFSfXRXf/Oew1gwCF3qs4L1Ux4y8eP8Kf/+F553vdMf5UX3iNP+P44MFsEpUOkhICE3DsyONSHs1FF8DLW0XQDtrwwAFQnz2KUOlutYzQr7VBeq24WtDf3eqACGvETpqIcqYr0bWNro=,iv:xyom8Rq405xZzienLxKUpbmeXJS/O0jSUFsZ3CakZ3s=,tag:lKywvKSzFgHdgDKo/EeD5A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
