kind: Secret
ansible_user: ENC[AES256_GCM,data:U+QMJg==,iv:LwUDjlgySXZHTJaq/qDPTdnpiawESoOEhs7kQv6q+o4=,tag:pZKyUneIa51iHR/6G8LPLw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lwA9sMLbDF4=,iv:zZxmbdAczTjd/ckv+IsnpRPhHnu0aI7VAZc7CEWukh8=,tag:sFSvT5Ey9rLTiNXJvBYe3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9wdnp870t9yy7ermhy0gq860mq2urq3fqrefut55v4tzwp3nurs43fg0s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Uk1UbHd2NXBDcnpxYjJv
            QjRnWUwvOGZIemFsWEpNWWtOK2l1UFZMZHhjClN4ekhMNXE5SXVVZDZmRU9KemxG
            SkVYWUhPUWNCY0M3R0pkcWJYQ25ENEEKLS0tIElYUG5HREhLOU9ObFFNQXhkYUp0
            eThrVVozczFvUHpvNFdpVzZiQWV1eUkKfjxiGP1InByo2qZvAQlJZzXjFmcZq/UQ
            zi7eMBPQF//nWpjRQSuVgTSOww1jkX7mNksWZIdjvtPDfAt/EQDgYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T14:29:39Z"
    mac: ENC[AES256_GCM,data:dmiUJV/7d9V3GDGDRT2DTiz1wKD4qCcjp9wls/W9bjmeSViIecEdtmVith8zfeCIWjDu2ds/0NEfkMG4Q1ht3FFg9lNV3iDQ7rjXDBoLK0a8a5BHOMfmZHpdCQhvUPb7Sc4x97ADXErtjNYenAm8MuozCgnpQk6Kz8isRTKmgV4=,iv:9HhelMpwjwV9y1Dbwyr3gZTJ+g041GqG76tDGAlQz0c=,tag:kD9e32dvB0uput5PrZImUA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
