kind: Secret
ansible_user: ENC[AES256_GCM,data:J30+HQ==,iv:OEVxIRk2b+CCzqllVdquQNKgqwQmrJ6Qvqvm+3fINsk=,tag:eGwszftCTZuKAIyNAA/9hg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vjFd8DocReE=,iv:Adyp2tZgRCMRSiBRg8elnaNXsSReWgPY1aU9Xqc2RQQ=,tag:B3p986zfnjPcED4hVHEPOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9wdnp870t9yy7ermhy0gq860mq2urq3fqrefut55v4tzwp3nurs43fg0s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0lZbW1yYmlFK25Jdkxk
            R0JDMVdpQWV4M1lNbUI3cHV0ZXRiV1FWTjM0CjJpdWRHdXpCcmI2dGhFM1FIM0lx
            ZEVrZ1ZtRU0yWjB0SnUyOXlJcW83RlkKLS0tIGxycEZlMUNZNGc3dExXTEY3bG95
            Y1dXWkxibnF1UG9xbWJjUFNzZ1ByMEEKM38rxUjujfGBBVu1G6XveJ2MMTDlA8tX
            kZbmKYUnQ61l/MzD4XJ239Sq44qOVx0j4YIMKMCJxoGq1aPIGPwC6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-22T06:58:13Z"
    mac: ENC[AES256_GCM,data:9KTInrXBtOxuqhNOawBKBRH6GGnrDdNg2PZRtm9NbIVRvjxwtKSss7bPdz7drCZnSczIpKMThPcHC+uSe7QhMOranmYjeK+ed+EfHA723Zcy6rTAXC+l0IYosPGauU1gAj3butgagnAyjxMPOicFyppTtgj+NeStldBeRoU+E9Y=,iv:4O6oVI1tdZmObu3TOHW1GCzd+aTmb0+gVye6hL6heNA=,tag:+rtiN9qztKvHA9FiVdVWUA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
