apiVersion: v1
kind: Service
metadata:
  labels:
    app: htpc
  name: ombi
  namespace: media
spec:
  ports:
  - name: webui
    port: 3579
    protocol: TCP
    targetPort: 3579
  selector:
    app: htpc
    run: ombi