# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:AC3TanjbQZR5mZjAtekNsg4kh94qTmYu2QDtpETcQdGMix5U+w==,iv:7PoSNLN00s5rhUF4vE840v5zAktQ9oVPdzPsmUdf70I=,tag:iaZMeezjgxLqyASxqlvpGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9wdnp870t9yy7ermhy0gq860mq2urq3fqrefut55v4tzwp3nurs43fg0s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTVFrb2Z5bHJ2YUJ1YjBF
            elpQQU9VRlhVWkptMWVycEJPSEFqaHlpRVdVCmhzRzZpL2xzLzNaMDFsUGJtUktT
            QlNYUWJySzFxcXBLaGEyOGRydkRTWjQKLS0tIDh5VExmZ0N4NXJsTUw4QzM1M0JV
            cWplZFNhTmU3TTRxY2NwZjFNc0Mya28KzFiOuxQDZ3tMr9jV5y2EGKLMBAHMHtrE
            u+gCnEvYkJUtcYCKhp9pw75OexmiFI/80Oygh17ADw9yagbJpxGmHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T14:29:39Z"
    mac: ENC[AES256_GCM,data:K0BXWdMSFqwoQo0jqyNNMjZHip8Dp/BGcgaeD7F135JWuueGRHBvpdawPVfLz/VDeVKW7274HWVt1Qq0piP+jTpxygXmBLVysWI9PqH4YfqlVg5YVOoOLCygjV3f153dRKnSdPXdDu65WqT6MS7hEc9lmZgdafe0GF/sG34ASo8=,iv:pCIWM9BxtyP1vQYkRv+IBGVtrOiJOxGygRG4I2jbt0c=,tag:dkK2w1JIhkz5aqaCLNqV/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
