apiVersion: v1
kind: Service
metadata:
  labels:
    app: htpc
  name: radarr
  namespace: media
spec:
  ports:
  - name: webui
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    app: htpc
    run: radarr