apiVersion: v1
kind: Service
metadata:
  labels:
    app: htpc
  name: deluge
  namespace: media
spec:
  ports:
  - name: webui
    port: 8112
    protocol: TCP
    targetPort: 8112
  selector:
    app: htpc
    run: deluge